#!/usr/bin/env python3
"""Download the webfonts the site uses and store them under assets/fonts/.

Self-hosting keeps every request on our own domain: no visitor IP address
reaches a Google server, which is the reason the fonts are not loaded from
fonts.googleapis.com. Run this only when a font is added or removed.

    python3 tools/fetch-fonts.py

Writes assets/fonts/*.woff2 plus assets/fonts-site.css and
assets/fonts-editor.css. Both CSS files are generated; do not edit them.
"""
import os
import re
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'assets', 'fonts')
UA = ('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
      '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36')

# Only these subsets are kept. latin covers English, German, French, Spanish
# and Italian; latin-ext adds Polish, Czech, Turkish and the rest of Europe.
KEEP = ('latin', 'latin-ext')

# Weight ranges rather than single weights: where a variable font exists,
# Google serves one file for the whole range instead of one file per weight.
SITE = [
    'Newsreader:opsz,wght@6..72,400..600',
    'IBM+Plex+Sans:wght@400..600',
]
EDITOR = [
    'Blinker:wght@400;600;700',
    'Nunito+Sans:wght@400..700',
    'Inter:wght@400..700',
    'Lato:wght@400;700',
    'Open+Sans:wght@400..700',
    'Montserrat:wght@400..700',
    'Raleway:wght@400..700',
    'Work+Sans:wght@400..700',
    'IBM+Plex+Sans:wght@400..700',
    'Source+Serif+4:wght@400..700',
    'Merriweather:wght@400..700',
    'Playfair+Display:wght@400..700',
    'EB+Garamond:wght@400..700',
    'Roboto+Slab:wght@400..700',
]


def fetch(url):
    return urllib.request.urlopen(
        urllib.request.Request(url, headers={'User-Agent': UA}), timeout=90).read()


def harvest(specs):
    faces = []
    seen = set()
    for spec in specs:
        css = fetch('https://fonts.googleapis.com/css2?family=%s&display=swap' % spec).decode()
        for block in re.split(r'(?=/\*\s*[a-z-]+\s*\*/)', css):
            head = re.match(r'/\*\s*([a-z-]+)\s*\*/', block.strip())
            if not head or head.group(1) not in KEEP or '@font-face' not in block:
                continue
            subset = head.group(1)
            family = re.search(r"font-family:\s*'([^']+)'", block).group(1)
            weight = re.search(r'font-weight:\s*([^;]+);', block).group(1).strip()
            url = re.search(r'url\((https://[^)]+)\)', block).group(1)
            name = '%s-%s-%s.woff2' % (family.lower().replace(' ', ''),
                                       weight.replace(' ', ''), subset)
            if name in seen:
                continue
            seen.add(name)
            path = os.path.join(OUT, name)
            if not os.path.exists(path):
                with open(path, 'wb') as fh:
                    fh.write(fetch(url))
            face = block[block.index('@font-face'):].strip()
            face = re.sub(r'url\(https://[^)]+\)', 'url(fonts/%s)' % name, face)
            faces.append('/* %s %s %s */\n%s' % (family, weight, subset, face))
    return faces


def write(path, title, faces):
    banner = ('/* %s\n   Generated by tools/fetch-fonts.py. Do not edit by hand. */\n\n'
              % title)
    with open(os.path.join(ROOT, 'assets', path), 'w') as fh:
        fh.write(banner + '\n\n'.join(faces) + '\n')
    print('%s — %d faces' % (path, len(faces)))


if __name__ == '__main__':
    os.makedirs(OUT, exist_ok=True)
    write('fonts-site.css', 'Webfonts for the site pages.', harvest(SITE))
    write('fonts-editor.css', 'Webfonts offered inside the editor.', harvest(EDITOR))
